name: Build, Test and Deploy .NET API

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ObjectEnvironmentPlacer.sln

    - name: Build
      run: dotnet build ObjectEnvironmentPlacer.sln --no-restore

    - name: Run Tests
      run: dotnet test ObjectEnvironmentPlacer.sln --no-build --verbosity normal

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: avansict2232402
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
