name: Build, Test and Deploy ASP.Net Core app to Azure Web App - avansict2232490

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ObjectEnvironmentPlacer.sln

      - name: Build solution
        run: dotnet build ObjectEnvironmentPlacer.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ObjectEnvironmentPlacer.sln --no-restore --verbosity normal

      - name: Publish app
        run: dotnet publish ./ObjectEnvironmentPlacer/ObjectEnvironmentPlacer.csproj -c Release -o publish_output


      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: publish_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish_output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A3C8538FB5EF4F40B3245513AF4ADF01 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_52668002BB47470B974C18CA97278109 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_294C705516A64E0E84BE0A03764C9E98 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'avansict2232490'
          slot-name: 'Production'
          package: ./publish_output
