name: Build, Test, and Deploy ASP.NET Core app to Azure Web App - EnvironmentPlacer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # 🔥 Your project is .NET 8.0!

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run Unit and System Tests 🧪
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish app
        run: dotnet publish -c Release -o '${{env.DOTNET_ROOT}}/myapp'

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build-and-test
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Azure Login 🔒
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Prefer using single JSON secret!

      - name: Deploy to Azure Web App 🚀
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EnvironmentPlacer'
          slot-name: 'Production'
          package: .
